import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#e4e2e1',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#f1f1ed',
        'surface-bright': '#faf9f5',
        'primary-fixed-dim': '#f9bb73',
        'primary-container': '#9c6a2a',
        background: '#faf9f5',
        outline: '#837567',
        'on-secondary-container': '#656464',
        'on-surface-variant': '#504539',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        tertiary: '#1f6284',
        surface: '#faf9f5',
        'surface-container': '#eeeeea',
        'surface-container-highest': '#e2e3df',
        'on-background': '#1a1c1a',
        'inverse-surface': '#2f312e',
        'tertiary-container': '#3d7b9e',
        'surface-variant': '#e2e3df',
        'on-secondary': '#ffffff',
        'primary-fixed': '#ffddba',
        'on-tertiary-container': '#fcfcff',
        'surface-tint': '#835416',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#93cef4',
        'surface-dim': '#dadad6',
        'on-secondary-fixed-variant': '#474747',
        'secondary-container': '#e4e2e1',
        error: '#ba1a1a',
        'surface-container-low': '#f4f4f0',
        'on-primary-fixed': '#2b1700',
        'on-tertiary-fixed-variant': '#004c6b',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#663d00',
        'surface-container-high': '#e8e8e4',
        'on-tertiary-fixed': '#001e2d',
        'tertiary-fixed': '#c6e7ff',
        'inverse-primary': '#f9bb73',
        'secondary-fixed-dim': '#c8c6c5',
        'on-surface': '#1a1c1a',
        primary: '#AF7A39',
        'on-primary-container': '#fffbff',
        'outline-variant': '#d5c4b4',
        secondary: '#5f5e5e',
        'on-secondary-fixed': '#1b1c1c',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
        newsreader: ['Newsreader', 'serif'],
        manrope: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.5rem',
        xl: '0.5rem',
        full: '9999px',
      },
    },
  },
} satisfies Config;
